jobs:
  fond.unifiedpool.all:
    chart_data_count: 6
    color:
      bot: 95
      top: 99
    id: 553
    pk: 25
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    chart_data_count: 20
    color:
      bot: 95
      top: 99
    id: 234
    pk: 12
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    chart_data_count: 20
    color:
      bot: 95
      top: 99
    id: 734
    pk: 32
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    chart_data_count: 30
    color:
      bot: 95
      top: 99
    id: 145
    pk: 7
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
FI_curr_RHEL6:
  fitrebus6:
    id: 08.08.2019
    pk: 1
LCOV:
  lcov_report_divided:
    id: '2019-08-10 11:07:35'
    path: http://asts-jenkins.moex.com/view/Coverage/job/lcov.rebus-curr.build/ws/coverage.report/index.html
    pk: 1
PATH: http://asts-jenkins.moex.com/job
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-08-13 09:45:05'
stand:
  astsplus@fitfond@spt5:
    id: '15.07.2019 04:51:23 / SwitchWBTest / '
    path: http://10.50.1.35:8080/ui/generic/stand?testuser=astsplus@fitfond@spt5&mode=list
    pk: 16
