PATH: http://asts-jenkins.moex.com/job/
color:
  bot: 95
  top: 99
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-06-24 14:37:27'
name:
  fond.unifiedpool.all:
    id: 519
    pk: 6
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    id: 220
    pk: 3
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    id: 693
    pk: 6
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    id: 137
    pk: 2
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
