PATH: http://asts-jenkins.moex.com/job/
color:
  bot: 95
  top: 99
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-06-21 13:58:32'
name:
  fond.unifiedpool.all:
    id: 517
    pk: 4
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    id: 219
    pk: 2
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    id: 692
    pk: 5
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    id: 136
    pk: 1
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
