PATH: http://asts-jenkins.moex.com/job/
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-07-03 10:12:22'
name:
  fond.unifiedpool.all:
    color:
      bot: 95
      top: 99
    id: 525
    pk: 12
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    color:
      bot: 95
      top: 99
    id: 222
    pk: 5
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    color:
      bot: 95
      top: 99
    id: 703
    pk: 16
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    color:
      bot: 95
      top: 99
    id: 138
    pk: 3
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
stand:
  id: '0'
  name: astsplus@fitfond@spt5
  path: http://10.50.1.35:8080/ui/generic/stand?testuser=astsplus@fitfond@spt5&mode=list
  pk: 0
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
