PATH: http://asts-jenkins.moex.com/job/
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-07-01 11:18:18'
name:
  fond.unifiedpool.all:
    color:
      bot: 95
      top: 99
    id: 523
    pk: 10
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    color:
      bot: 95
      top: 99
    id: 222
    pk: 5
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    color:
      bot: 95
      top: 99
    id: 701
    pk: 14
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    color:
      bot: 95
      top: 99
    id: 138
    pk: 3
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
