PATH: http://asts-jenkins.moex.com/job/
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-06-28 14:06:02'
name:
  fond.unifiedpool.all:
    color:
      bot: 95
      top: 99
    id: 522
    pk: 9
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    color:
      bot: 95
      top: 99
    id: 221
    pk: 4
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    color:
      bot: 95
      top: 99
    id: 700
    pk: 13
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    color:
      bot: 95
      top: 99
    id: 137
    pk: 2
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
