PATH: http://asts-jenkins.moex.com/view/Rebus/job/
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-06-14 10:11:27'
name:
  rebus.all:
    id: 687
    pk: 2
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
