PATH: http://asts-jenkins.moex.com/job/
db:
  db_name: testresults
  host: db
  port: 27017
last_update: '2019-06-20 14:29:28'
name:
  fond.unifiedpool.all:
    id: 517
    pk: 1
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  fond.unifiedpool.all.long:
    id: 218
    pk: 1
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all:
    id: 692
    pk: 1
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
  rebus.all.long:
    id: 136
    pk: 1
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: Jenpass11-goodpass
  username: Oleshko_Alexander
