PATH: http://127.0.0.1:8001/job/
db:
  host: "127.0.0.1"
  port: 27017
  db_name: testresults
name:
  test:
    id: 64
    pk: 48
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
