PATH: http://127.0.0.1:8001/job/
db:
  db_name: testresults
  host: 127.0.0.1
  port: 27017
last_update: '2019-04-26 14:35:01'
name:
  test:
    id: 67
    pk: 52
    to_sum:
      1:
      - Tests
      - SmokeTests
      2:
      - FunctionalTests
user:
  password: password
  username: new_user
