version: '3'

services:
  web:
    build: .
    networks:
      - net
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
    depends_on: 
      - db
  db: 
    image: mongo:4.1
    ports:
      - "27015:27017"
    networks:
      - net
networks:
  net:
