version: '3'

services:
  web:
    build: .
    networks:
      - net
    ports: 
      - "80:80"
    volumes:
      - .:/code
    depends_on: 
      - db
  db: 
    image: mongo:4.1
    networks:
      - net
networks:
  net:
