version: '3'

services:
  web:
    build: .
    networks:
      - net
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
    depends_on: 
      - db
  db: 
    image: mongo:4.1
    command: --auth
    networks:
      - net
    volumes:
      - /dump:/dump
  restore_db:
    image: mongo:4.1
    volumes: 
      - ./dump:/dump
    entrypoint: ["mongorestore", "--host", "db", "/dump"]
    networks:
      - net
networks:
  net:
