version: '3'

services:
  web:
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - .:/code
    network_mode: "host"
    depends_on: 
      - db
  db: 
    image: mongo:4.1
    ports:
      - "27017:27017"        
